version: '3.9'

services:
  api:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./docker_config.py:/code/default_config.py
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name

